---
clusterName: talos-test
endpoint: https://192.168.0.11:6443
talosVersion: v1.9.5
nodes:
  - hostname: talos-test-cp-01
    controlPlane: true
    ipAddress: 192.168.0.11
    installDisk: /dev/sda
    nameserver:
      - time.cloudflare.com
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses:
        - 192.168.0.11/24
        routes:
          - gateway: 192.168.0.1
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/qemu-guest-agent
  - hostname: talos-test-worker-01
    controlPlane: false
    ipAddress: 192.168.0.12
    installDisk: /dev/sda
    nameserver:
      - time.cloudflare.com
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses:
        - 192.168.0.12/24
        routes:
          - gateway: 192.168.0.1
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/qemu-guest-agent
  - hostname: talos-test-worker-02
    controlPlane: false
    ipAddress: 192.168.0.13
    installDisk: /dev/sda
    nameserver:
      - time.cloudflare.com
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses:
        - 192.168.0.13/24
        routes:
          - gateway: 192.168.0.1
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/qemu-guest-agent
patches:
  - "@./patches/patch.yaml"
