---
clusterName: talos-mgmt
endpoint: https://192.168.0.17:6443
talosVersion: v1.10.5
allowSchedulingOnControlPlanes: true
nodes:
  - hostname: talos-mgmt-cp-01
    controlPlane: true
    ipAddress: 192.168.0.17
    installDisk: /dev/sda
    nameserver:
      - time.cloudflare.com
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses:
        - 192.168.0.17/24
        routes:
          - gateway: 192.168.0.1
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/qemu-guest-agent
patches:
  - "@./patches/patch.yaml"
